"""add rate limit columns to users

Revision ID: 37c04f4bbf54
Revises: ad01d3c7de2a
Create Date: 2026-05-31 14:05:58.070577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c04f4bbf54'
down_revision: Union[str, None] = 'ad01d3c7de2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_message_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_message_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_date')
    op.drop_column('users', 'daily_message_count')
    # ### end Alembic commands ###
